name       : qt6-datavis3d
version    : 6.3.0
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtdatavis3d-everywhere-src-6.3.0.tar.xz : 09512ef3b2b28ff8defaea96498736418ada008f3778220a9185c09dd59e0d8d
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Data Visualization module
description: |
    Qt Data Visualization module provides multiple graph types to visualize data in 3D space both with C++ and QML.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
