name       : qt6-datavis3d
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtdatavis3d-everywhere-src-6.2.2.tar.xz : 3394df51e86c11edc3c2727856f5ad79a720d72a1abc24b88f11e755d872f123
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Data Visualization module
description: |
    Qt Data Visualization module provides multiple graph types to visualize data in 3D space both with C++ and QML.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
